### ISSUE TITLE
What is difference between Index and PQFlashIndex?

### ISSUE THREAD

**Issue by eggchai** [microsoft/DiskANN#113]
In tests/build_disk_index use Index, and in tests/search_disk_index use PQFlashIndex;
In tests/build_memory_index use PQFlashIndex, and in tests/search_disk_index.

Why Index and PQFlashIndex work together?

**Comment by harsha-simhadri** [comment]
Index is for in-memory serving/building. PQFlashIndex is for SSD based serving
