### ISSUE TITLE
missing "float"

### ISSUE THREAD

**Issue by yushangdi** [microsoft/DiskANN#164]
The commands in workflow/in_memory_index.md seems to be missing type args.

./tests/utils/fvecs_to_bin float data/sift/sift_learn.fvecs data/sift/sift_learn.fbin
./tests/utils/fvecs_to_bin float data/sift/sift_query.fvecs data/sift/sift_query.fbin

instead of 

./tests/utils/fvecs_to_bin data/sift/sift_learn.fvecs data/sift/sift_learn.fbin
./tests/utils/fvecs_to_bin data/sift/sift_query.fvecs data/sift/sift_query.fbin

**Comment by harsha-simhadri** [comment]
Earlier float was the only option. Support for other types was recently added. We will change the examples

**Comment by harsha-simhadri** [comment]
https://github.com/microsoft/DiskANN/pull/168
