### ISSUE TITLE
PR Template 

### ISSUE THREAD

**Issue by cybergeekgyan** [microsoft/DiskANN#171]
Thanks for contributing a pull request! Please ensure you have taken a look at
the contribution guidelines:

 [Contributing.md](https://github.com/microsoft/graspologic/blob/dev/CONTRIBUTING.md)

- [ ] Does this PR have a descriptive title that could go in our release notes?
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### Reference Issues/PRs

Example: Fixes #1234. See also #3456.
Please use keywords (e.g., Fixes) to create link to the issues or pull requests
you resolved, so that they will automatically be closed when your pull request
is merged. See [Link](https://github.com/blog/1506-closing-issues-via-pull-requests)

#### Any other comments?

**Comment by harsha-simhadri** [comment]
https://github.com/microsoft/DiskANN/pull/178
