### ISSUE TITLE
What’s the use of frozen points?

### ISSUE THREAD

**Issue by HannanKan** [microsoft/DiskANN#23]
During reading source code of DiskANN, I notice a new concept, frozen points, which does not show up in DiskANN paper. I wonder what's the use of frozen points. Hope for your reply!

**Comment by ShikharJ** [comment]
@Hannankan I believe they're just for ignoring certain points in the dataset that have known issues with them. For example, null vectors and corrupted points.

**Comment by HannanKan** [comment]
So after removing these points, serial number of other points have to be changed accordingly, right?
