### ISSUE TITLE
Why is the performance of DiskANN on Yandex Text-to-Image* dataset limited？

### ISSUE THREAD

**Issue by HannanKan** [microsoft/DiskANN#25]
I have recently participated NeurIPS competition ([link here](http://big-ann-benchmarks.com/)). Competition homepage shows that recall of DiskANN on Yandex Text-to-Image dataset is limited to 48.8%. Norm of query vectors are all 1 and norms of base vector are between 0.758 and 0.993. Could you please tell me why DiskANN do not perform well? R and L parameters set to 100.

**Comment by ShikharJ** [comment]
@Hannankan This is a research question to which even we are looking for an answer 😄 I promise to tell you as soon as I know for sure.

**Comment by harsha-simhadri** [comment]
Issue researched and possible fix in https://arxiv.org/abs/2211.12850
Code to follow.
