### ISSUE TITLE
Support search by multiple filters for a query file

### ISSUE THREAD

**Issue by dkaczynski** [microsoft/DiskANN#265]
Do we want to allow query-specific filter labels in this tool by, say, passing a file with a filter for each query. Isnt that more natural than filtering by the same label for all queries? Same question for search_memory_index.

_Originally posted by @harsha-simhadri in https://github.com/microsoft/DiskANN/pull/225#discussion_r1116330685_

**Comment by yashpatel007** [comment]
Varun is working on this at  varunsivashankar/support_multiple_filterlabels
