### ISSUE TITLE
Update codebase to C++17 Standards

### ISSUE THREAD

**Issue by dkaczynski** [microsoft/DiskANN#268]
Can we just use https://en.cppreference.com/w/cpp/filesystem/copy_file rather than write our own here?

_Originally posted by @harsha-simhadri in https://github.com/microsoft/DiskANN/pull/225#discussion_r1096298234_

**Comment by daxpryce** [comment]
Would it be crazy to try to achieve C++ 20?  I would *love* to just used named parameters in lieu of some of the parameter objects we have.

**Comment by harsha-simhadri** [comment]
I am ok with C++20. @dkaczynski @yashpatel007  ?
