### ISSUE TITLE
broken link to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by pabs3** [microsoft/DiskANN#30]
The link to `CONTRIBUTING.md` in the `README.md` is broken because the file is called `CONTRIBUTING.MD` (uppercase `.MD` instead) and many filesystems and also GitHub URLs are case-sensitive.

I suggest the right fix would be to rename `CONTRIBUTING.MD` (uppercase `.MD`) to `CONTRIBUTING.md` (lowercase `.md`).

**Comment by harsha-simhadri** [comment]
fixed, thanks
