### ISSUE TITLE
[Question] Not support insert and delete in disk index?

### ISSUE THREAD

**Issue by bytetopia** [microsoft/DiskANN#314]
Thanks for making the code open source! I got a question while reading the code, seems that insert and update operations are only supported in memory index now? For disk index, current code only supports build and search?

**Comment by harsha-simhadri** [comment]
We plan to support a bulk merge of inserts/deletes into SSD index. Not point changes, that is best done through in-mem index.

**Comment by bytetopia** [comment]
Thanks for the reply! @harsha-simhadri Do you mean that for SSD index, there won't be point level inserts/deletes supported (TempIndex/DeleteList as the FreshDiskANN paper mentioned) but bulk merge directly into SSD? Not sure whether my understanding is correct.
