### ISSUE TITLE
`clang-format-4.0` package in `README.md` is outdated

### ISSUE THREAD

**Issue by pabs3** [microsoft/DiskANN#33]
The `clang-format-4.0` package mentioned in `README.md` is no longer available in recent Debian based distributions, the latest release it is present in is Debian stretch and Ubuntu bionic.

I suggest to replace it with `clang-format` instead, which is a meta-package that pulls in the most recent version of `clang-format` available in the current distro release.

**Comment by harsha-simhadri** [comment]
fixed

**Comment by pabs3** [comment]
Thanks.

BTW a better way to close issues is to do it in the commit message,
just include the word "Fixes", a colon and the full issue URL:

Fixes: https://github.com/microsoft/DiskANN/issues/33

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
