### ISSUE TITLE
git conflict marker `<<<<<<< HEAD` in `.gitignore`

### ISSUE THREAD

**Issue by pabs3** [microsoft/DiskANN#34]
The `.gitignore` file has a `<<<<<<< HEAD` git conflict marker introduced in commit 4084c296636749dcf7b3c706cdceb1cd45467e2d.

I suggest that it should be removed.

**Comment by harsha-simhadri** [comment]
Absent in latest commit

**Comment by pabs3** [comment]
Looks like commit e3a29acac734798f539db30296152ed30908c2c2 incidentally fixed it.

Generally it is a good idea to make logical commits with git rather
than committing several unrelated things in the same commit.

https://github.com/git-guides/git-commit
https://benmatselby.dev/post/logical-commits/
***@***.***/the-zeotech-series-git-workflow-rebase-vs-merge-93cf0866ed35
https://www.lullabot.com/articles/git-best-practices-workflow-guidelines

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
