### ISSUE TITLE
[Question] How can we download Turing Text-to-img datasets

### ISSUE THREAD

**Issue by chasingegg** [microsoft/DiskANN#386]
In this paper: OOD-DiskANN: Efficient and Scalable Graph ANNS for Out-of-Distribution Queries, Experiment part uses some text2img datasets include Yandex Text-to-Img (can be found in https://big-ann-benchmarks.com/) and Turing Text-to-Img, but I can not find Turing Text-to-Img, is it open sourced?

**Comment by harsha-simhadri** [comment]
Please see the README in big-ann-benchmarks.com. There is a tool called create_dataset.py to download the file
