### ISSUE TITLE
[Question] Code branch of OOD-DiskANN

### ISSUE THREAD

**Issue by matchyc** [microsoft/DiskANN#406]
Dear authors,
I'm trying to reproduce the result of OOD-DiskANN. ​
I'm using the branch named "ood-queries" (https://github.com/microsoft/DiskANN/tree/ood-queries ), I have seen the codes inside `link()` match the algorithm description in OOD-DiskANN paper. I want to make sure the branch I used is the right one, and the build and search scripts in cpp are build_with_query_data.cpp and search_memory_index_dynamic.cpp.

Thank you in advance!

**Comment by harsha-simhadri** [comment]
The branch you quoted is a variant of ideas explored in the OOD-DISKANN paper. the code for OOD-DiskANN is yet to be well integrated into this repo
