### ISSUE TITLE
[Question] Which Vamana Graph is used by the Disk Version of the Filterd-DiskANN Code？

### ISSUE THREAD

**Issue by Coien-rr** [microsoft/DiskANN#413]
As in [Memory Filterd-DiskANN](https://github.com/microsoft/DiskANN/blob/main/workflows/filtered_in_memory.md), There are two compositional approaches here, Filterd-Vamana and Stitched-Vamana, as proposed in the paper [Filtered-DiskANN](https://harsha-simhadri.org/pubs/Filtered-DiskANN23.pdf)

But in the [filtered_ssd_index.md](https://github.com/microsoft/DiskANN/blob/main/workflows/filtered_ssd_index.md), there are not any configuration for two different compositional approaches.

So, I'd like to ask
1. **What kind of composition method the disk version uses?** 
2. **Whether the future will support multiple composition methods?**

**Comment by rakri** [comment]
Hi, it uses the filetered vamana (approach 1 you suggest). We will definitely add a way to build a disk index using method 2 sometime soon,
