### ISSUE TITLE
[Question] Only support 1000 filters ?

### ISSUE THREAD

**Issue by shiwanghua** [microsoft/DiskANN#420]
What do you mean by one filter ? Such as ' $A_i$ =19 ' (a attribute no and a value) a filter ?

In my opinion, the attribute number tends to be a big number, and each attribute has lots of values.
For example, there are 10000 attributes and each atttribute has 10~10000 different values.
However, each vector has 0\~500 attribute value while other attributes are null value.

In this very common case, are both FilteredVamana and StitchedVamana not suitable ?
If so, I don't think this algorithm has much practical significance.

<img width="654" alt="image" src="https://github.com/microsoft/DiskANN/assets/29914854/d0503f7c-ddfd-44f1-a3a0-16eefb8f43c1">

**Comment by harsha-simhadri** [comment]
Can you please clarify your question? Specifically, what is $A_i$ in the context of your question? 

I think the notion of filter is defined in the paper.  Are you proposing a new notion, or suggesting the definition in the paper is not well defined?

**Comment by shiwanghua** [comment]
> Can you please clarify your question? Specifically, what is Ai in the context of your question?
> 
> I think the notion of filter is defined in the paper. Are you proposing a new notion, or suggesting the definition in the paper is not well defined?

Thanks for reply.

Ai means the i-th attribute.

I have only found the notion of filter in the header of 1.1:

<img width="586" alt="image" src="https://github.com/microsoft/DiskANN/assets/29914854/cb945687-eede-4a40-9fd9-29de1000ecd6">

$\mathcal{F}$ can be seen as one attribute and there is only one attribute in the domain. 
It's OK because each vector can have several values/labels/tags. 
This model can be called "Single attribute & Multiple values".

But what ever, that is not the point.

I question about the total number of suppported labels being too small.

**Comment by harsha-simhadri** [comment]
The paper and the code support what you point in the snippet above as of today.
