### ISSUE TITLE
[Question] What does specificity |Pf|/|P| mean ?

### ISSUE THREAD

**Issue by shiwanghua** [microsoft/DiskANN#423]
"the specificity |𝑃𝑓 |/|𝑃 | of the 100, 75, 50, 25 and 1 percentile filters as sorted in decreasing order of frequency."

<img width="1246" alt="image" src="https://github.com/microsoft/DiskANN/assets/29914854/5ba8a01c-c9b1-47b0-b0e8-327607fef0e0">

Does the 0.127 means the number of 100% points' filters is 0.127*n ?

"decreasing order of frequency", what does the frequency mean ?
* the frequency of filter(label no) ?
* the frequency of the number of filter of one point ?

**Comment by harsha-simhadri** [comment]
0.127 specificity means that 0.127*n vectors (where n is total #vectors) have that label
