### ISSUE TITLE
[BUG] diskannpy: batch_search is mistyped

### ISSUE THREAD

**Issue by bddap** [microsoft/DiskANN#433]
## Expected Behavior

According to its [type annotations](https://github.com/microsoft/DiskANN/blob/4162c2118908cf55e719c0cdfdcd50b9069bef8f/python/src/_static_disk_index.py#L148), `batch_search` is expected to return a named tuple.

## Actual Behavior

It returns a normal tuple.

**Comment by bddap** [comment]
Might want to check [static_memory_index](https://github.com/microsoft/DiskANN/blob/4162c2118908cf55e719c0cdfdcd50b9069bef8f/python/src/_static_memory_index.py#L141) and [_dynamic_memory_index](https://github.com/microsoft/DiskANN/blob/4162c2118908cf55e719c0cdfdcd50b9069bef8f/python/src/dynamic_memory_index.py#L316) too.

**Comment by daxpryce** [comment]
Oh man thank you for this.  I'll get a fix out asap
