### ISSUE TITLE
[Question] DiskANN QPS is based on a batch, singular query, or something else?

### ISSUE THREAD

**Issue by rifqifarhansyah** [microsoft/DiskANN#449]
If i run the command "./apps/search_disk_index --data_type float --dist_fn l2 --index_path_prefix data/sift/disk_index_sift_learn_R32_L50_A1.2 --query_file data/sift/sift_query.fbin --gt_file data/sift/sift_query_learn_gt100 -K 10 -L 10 20 30 40 50 100 --result_path data/sift/res --num_nodes_to_cache 500000 -T 1", i got the result below. Is the QPS is the throughput result for a batch, singular query, or something else?

     L   Beamwidth             QPS    Mean Latency    99.9 Latency        Mean IOs         CPU (s)       Recall@10
======================================================================================================================
    10           2        11237.96           50.43          116.00            0.00           19.50           80.38
    20           2        10311.63           64.38           97.00            0.00           27.35           95.43
    30           2         8188.90           88.60          131.00            0.00           37.01           98.18
    40           2         6772.91          112.50          155.00            0.00           46.76           98.99
    50           2         5767.28          136.77          529.00            0.00           56.65           99.36
   100           2         3343.72          255.74          670.00            0.00          106.43           99.84

**Comment by harsha-simhadri** [comment]
QPS = number of quries divided by the time needed to process all queries in the file. Since you ran with 1 thread, the average time per single query would be 1/QPS.
