### ISSUE TITLE
How DiskANN initialize the beginning random graph?

### ISSUE THREAD

**Issue by symphony233** [microsoft/DiskANN#53]
Hi, I'm working on some evaluations of the DiskANN code. But I can't figure out how the DiskANN builds the very first stage graph as it is described in the paper. I also checked the `link()` function, but I got nothing about the random initialization.

**Comment by harsha-simhadri** [comment]
The code has evolved since the paper. We figured the randomness in the graph initialization may not be necessary if you shuffle the data before building it.
